### ISSUE TITLE
Smooth contact form transition

### ISSUE THREAD

**Issue by ralfz123** [DikkeTimo/fix-the-flow-interactive-website#1]
Add an initial width to the `.contact. class and a transition to the `.toggle` class, like below

```css
.contact {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 0 auto;
  width: 100px;
}

.toggle {
  margin: 0 auto;
  transition: 1s ease-in-out all;
}
```
